/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ExercisesIndexImport } from './routes/exercises/index'
import { Route as ExercisesIdImport } from './routes/exercises/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExercisesIndexRoute = ExercisesIndexImport.update({
  path: '/exercises/',
  getParentRoute: () => rootRoute,
} as any)

const ExercisesIdRoute = ExercisesIdImport.update({
  path: '/exercises/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/exercises/$id': {
      preLoaderRoute: typeof ExercisesIdImport
      parentRoute: typeof rootRoute
    }
    '/exercises/': {
      preLoaderRoute: typeof ExercisesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ExercisesIdRoute,
  ExercisesIndexRoute,
])

/* prettier-ignore-end */
